### ISSUE TITLE
最新版 win10 21h2 19044.2130 不支持

### ISSUE THREAD

**Issue by LYingSiMon** [FiYHer/InfinityHookPro#17]
您好，这个项目真的很棒和😁

失败的原因应该是 find_pattern_image 没有查找到特征码，因为这个问题在较早版本的 21h2 上不会出现。
![QQ图片20221022005659](https://user-images.githubusercontent.com/51651107/197249283-7b1a7733-7446-458e-a33f-3d74a9344a56.jpg)

我尝试卸载更新，最后确定是如下这个更新导致的问题（KB5018410）：
![360截图17891230919080](https://user-images.githubusercontent.com/51651107/197249784-3d38652b-1816-4980-86b2-7e94182fd288.png)

希望可以得到您的答复。

**Comment by FiYHer** [comment]
> 您好，这个项目真的很棒和😁
> 
> 失败的原因应该是 find_pattern_image 没有查找到特征码，因为这个问题在较早版本的 21h2 上不会出现。 ![QQ图片20221022005659](https://user-images.githubusercontent.com/51651107/197249283-7b1a7733-7446-458e-a33f-3d74a9344a56.jpg)
> 
> 我尝试卸载更新，最后确定是如下这个更新导致的问题（KB5018410）： ![360截图17891230919080](https://user-images.githubusercontent.com/51651107/197249784-3d38652b-1816-4980-86b2-7e94182fd288.png)
> 
> 希望可以得到您的答复。

最近不想动这个demo，你自己琢磨吧，看得出来你水平也很高，认真琢磨下应该没问题。

**Comment by LYingSiMon** [comment]
我没有仓库权限，抱歉只能写在这里，依照你说的，我修正了它
```
/* 这里我们查找到HvlGetQpcBias的指针
			*   详细介绍可以看https://www.freebuf.com/articles/system/278857.html
			*	win10 21h2.2130 安装 KB5018410 补丁后需要使用新的特征码
			*/
			address = k_utils::find_pattern_image(ntoskrnl,
				"\x48\x8b\x05\x00\x00\x00\x00\x48\x85\xc0\x74\x00\x48\x83\x3d\x00\x00\x00\x00\x00\x74",
				"xxx????xxxx?xxx?????x");
			if (!address) address = k_utils::find_pattern_image(ntoskrnl,
				"\x48\x8b\x05\x00\x00\x00\x00\xe8\x00\x00\x00\x00\x48\x03\xd8\x48\x89\x1f",
				"xxx????x????xxxxxx");
			if (!address) return false;
			g_HvlGetQpcBias = reinterpret_cast<unsigned long long>(reinterpret_cast<char*>(address) + 7 + *reinterpret_cast<int*>(reinterpret_cast<char*>(address) + 3));
			if (!g_HvlGetQpcBias) return false;
			DbgPrintEx(0, 0, "[%s] hvl get qpc bias is 0x%llX \n", __FUNCTION__, g_HvlGetQpcBias);
```

希望这个项目能变得越来越好。
