### ISSUE TITLE
在Win7上,刚Start Hook时，钩子可以正常工作，但等一会钩子就无效了，大概等5-10分钟

### ISSUE THREAD

**Issue by wqwinking** [FiYHer/InfinityHookPro#19]
在Win7上挂SSDT钩子后，钩子可以正常工作，但是等一会（大概5-10分钟之后），钩子就无效了

**Comment by FiYHer** [comment]
> 在Win7上挂SSDT钩子后，钩子可以正常工作，但是等一会（大概5-10分钟之后），钩子就无效了

今天版本已修复
