### ISSUE TITLE
Win 11 22000.258 启动成功不进入钩子

### ISSUE THREAD

**Issue by ashyerv** [FiYHer/InfinityHookPro#6]
启动,不进入钩子,系统版本号：
22000.258 / Windows 功能体验包 1000.22000.258.0

Microsoft Windows [版本 10.0.22000.258]
(c) Microsoft Corporation。保留所有权利。

C:\Users\*>

不进钩子,特意看了一下IDA下面的字节,发现都是能搜索到的.原因不明,特来请教一下

![QQ图片20220322182318](https://user-images.githubusercontent.com/101718937/159459909-9c381ae5-ad01-4277-aeb0-beded91f09cc.png)

(为了确保能用,我特意选了这个版本,并未安装任何补丁,驱动签名的是过期驱动但尚未吊销)

![SPL@X_WW4}}1@CA9J_WY}QL](https://user-images.githubusercontent.com/101718937/159461277-425484ff-d2a6-49f6-bbc7-8dbe5f7b171c.png)

**Comment by FiYHer** [comment]
> 启动,不进入钩子,系统版本号： 22000.258 / Windows 功能体验包 1000.22000.258.0
> 
> Microsoft Windows [版本 10.0.22000.258] (c) Microsoft Corporation。保留所有权利。
> 
> C:\Users*>
> 
> 不进钩子,特意看了一下IDA下面的字节,发现都是能搜索到的.原因不明,特来请教一下
> 
> ![QQ图片20220322182318](https://user-images.githubusercontent.com/101718937/159459909-9c381ae5-ad01-4277-aeb0-beded91f09cc.png)
> 
> (为了确保能用,我特意选了这个版本,并未安装任何补丁,驱动签名的是过期驱动但尚未吊销)
> 
> ![SPL@X_WW4}}1@CA9J_WY}QL](https://user-images.githubusercontent.com/101718937/159461277-425484ff-d2a6-49f6-bbc7-8dbe5f7b171c.png)

你是像我那样打开一个tips.txt来验证的么？

**Comment by ashyerv** [comment]
在 Win 10下都是正常的。
已测试系统是 WIN10 20H2

**Comment by ashyerv** [comment]
test video
https://user-images.githubusercontent.com/101718937/159823991-88c2e286-ddf4-4378-9f18-ee4a65880e3e.mp4

**Comment by FiYHer** [comment]
> test video (不知道为什么chrome不能直接在线播放...) 在WIN 8/10下都正常，非常抱歉给你添麻烦了
> 
>  video.mp4

嗯,可能确实是某些数据结构或者其它东西发生了改变
现在不太想动这个项目了,代码逻辑和注释都蛮清晰的,你尝试自己调试看看吧,代码也不算多吧
