### ISSUE TITLE
win11 正式版HOOK无效

### ISSUE THREAD

**Issue by kx500** [FiYHer/InfinityHookPro#7]
win11 正式版 call_back 没有执行

**Comment by FiYHer** [comment]
> win11 正式版 call_back 没有执行

![1](https://user-images.githubusercontent.com/25883177/176366161-d9ee71c6-24f7-4a16-bc36-b6a36483bbd7.JPG)

最新版Win11,测试有效

**Comment by kx500** [comment]
我&nbsp; HOOK的是&nbsp;NtDeviceIoControlFile ，不信你试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月29日(星期三) 下午2:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FiYHer/InfinityHookPro] win11 正式版HOOK无效 (Issue #7)





  
win11 正式版 call_back 没有执行
  

 
最新版Win11,测试有效
